### ISSUE TITLE
Ce projet github est-il toujours maintenu ?

### ISSUE THREAD

**Issue by cinlloc** [fabmob/mob#19]
Ce projet github est-il toujours maintenu ? (pas d'activité depuis 3 mois)
Sinon, le code est-il disponible ailleurs ? 
Merci de votre aide.

**Comment by TTalex** [comment]
Bonjour @cinlloc 
Le projet est maintenu, mais le code github n'est en effet pas tout à fait à jour.
Nous avons changé d'équipe de développement ces 3 derniers mois, et nous sommes en cours de migration des pipelines de publication.
C'est donc une question de temps, mais une mise à jour de ce repo est prévue.

Note: Tout de même, toute la logique autour du CEE coup de pouce covoiturage est la même qu'en production à date.

**Comment by cinlloc** [comment]
Merci pour la réponse :pray:
